server:
  port: 28080
  servlet:
    context-path: /shop
    session:
      timeout: 1800

spring:
  profiles:
    active: local
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shopdb
    username: root
    password: 1111
  mail:
    host: smtp.gmail.com
    port: 587
    username: sljh1020@gmail.com
    password: pizaagtsvukoenfy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  activemq:
    packages:
      trust-all: true
  thymeleaf:
    prefix: classpath:/templates/mail/
    suffix:  .html
    mode: HTML
    encoding: UTF-8
    check-templates: true
    view-names: thymeleaf/*
  sms:
    from: 01052386416
    apiKey: NCSC4PBSVBEEAKPQ
    apiSecret: QDQVVJIAJOE4OCHIXN1MDPQTFFKMGZXM
  pay:
    key:
      apiKey: 2101734355174268
      apiSecretKey: f7VWu9wmMtInrcEYo3wtwCJ9PDsvxrLlHSUiz9Mxg1ZW0i9iAbQK3JYJr4euL00Bn0qVzUNYPlwG8Y1H
    url:
      getToken: https://api.iamport.kr/users/getToken
      paymentInfo: https://api.iamport.kr/payments/
      paymentCancel: https://api.iamport.kr/payments/cancel



