server:
  port: 8070
  servlet:
    context-path: /developer

spring:
  profiles:
    active: local
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/bootdb
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  session:
    jdbc:
      initialize-schema: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: sljh1020@gmail.com
    password: pizaagtsvukoenfy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

