server:
  port: 28080
  servlet:
    context-path: /shop

spring:
  profiles:
    active: local
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shopdb
    username: root
    password: 1111
  mail:
    host: smtp.gmail.com
    port: 587
    username: sljh1020@gmail.com
    password: pizaagtsvukoenfy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

